// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (api_key_hash, name, balance)
VALUES ($1, $2, 0)
RETURNING id, api_key_hash, name, balance, created_at, updated_at
`

type CreateAccountParams struct {
	ApiKeyHash string `json:"api_key_hash"`
	Name       string `json:"name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ApiKeyHash, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByAPIKeyHash = `-- name: GetAccountByAPIKeyHash :one
SELECT id, api_key_hash, name, balance, created_at, updated_at
FROM accounts
WHERE api_key_hash = $1
`

func (q *Queries) GetAccountByAPIKeyHash(ctx context.Context, apiKeyHash string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByAPIKeyHash, apiKeyHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, api_key_hash, name, balance, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = $2, updated_at = now()
WHERE id = $1
RETURNING id, api_key_hash, name, balance, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID      uuid.UUID `json:"id"`
	Balance int64     `json:"balance"`
}

// Used only by the reconciler / cold-start bootstrap to align the Postgres-cached
// balance with SUM(ledger_entries). The hot-path debit/credit itself happens in
// Redis (see ARCHITECTURE.md section 5) and is durably recorded via ledger_entries.
func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
