// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: accounts.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (api_key_hash, name, balance)
VALUES ($1, $2, 0)
RETURNING id, api_key_hash, name, balance, created_at, updated_at
`

type CreateAccountParams struct {
	ApiKeyHash string `json:"api_key_hash"`
	Name       string `json:"name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.ApiKeyHash, arg.Name)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByAPIKeyHash = `-- name: GetAccountByAPIKeyHash :one
SELECT id, api_key_hash, name, balance, created_at, updated_at
FROM accounts
WHERE api_key_hash = $1
`

func (q *Queries) GetAccountByAPIKeyHash(ctx context.Context, apiKeyHash string) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByAPIKeyHash, apiKeyHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, api_key_hash, name, balance, created_at, updated_at
FROM accounts
WHERE id = $1
`

func (q *Queries) GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAccountIDs = `-- name: ListAccountIDs :many
SELECT id FROM accounts
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListAccountIDsParams struct {
	ID    uuid.UUID `json:"id"`
	Limit int32     `json:"limit"`
}

// Keyset pagination for reconciler sweeps (pass uuid.Nil for the first page).
func (q *Queries) ListAccountIDs(ctx context.Context, arg ListAccountIDsParams) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listAccountIDs, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountBalance = `-- name: UpdateAccountBalance :one
UPDATE accounts
SET balance = $2, updated_at = now()
WHERE id = $1
RETURNING id, api_key_hash, name, balance, created_at, updated_at
`

type UpdateAccountBalanceParams struct {
	ID      uuid.UUID `json:"id"`
	Balance int64     `json:"balance"`
}

// Aligns Postgres-cached balance with SUM(ledger_entries). Hot-path debit/credit
// is Redis (ARCHITECTURE.md section 5); ledger_entries is durable ground truth.
func (q *Queries) UpdateAccountBalance(ctx context.Context, arg UpdateAccountBalanceParams) (Account, error) {
	row := q.db.QueryRow(ctx, updateAccountBalance, arg.ID, arg.Balance)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ApiKeyHash,
		&i.Name,
		&i.Balance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
