// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: campaigns.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (id, account_id, text, total_recipients, cost_per_message, total_cost, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO NOTHING
RETURNING id, account_id, text, total_recipients, cost_per_message, total_cost, status, created_at, updated_at
`

type CreateCampaignParams struct {
	ID              uuid.UUID `json:"id"`
	AccountID       uuid.UUID `json:"account_id"`
	Text            string    `json:"text"`
	TotalRecipients int32     `json:"total_recipients"`
	CostPerMessage  int64     `json:"cost_per_message"`
	TotalCost       int64     `json:"total_cost"`
	Status          string    `json:"status"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.ID,
		arg.AccountID,
		arg.Text,
		arg.TotalRecipients,
		arg.CostPerMessage,
		arg.TotalCost,
		arg.Status,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Text,
		&i.TotalRecipients,
		&i.CostPerMessage,
		&i.TotalCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCampaignByID = `-- name: GetCampaignByID :one
SELECT id, account_id, text, total_recipients, cost_per_message, total_cost, status, created_at, updated_at
FROM campaigns
WHERE id = $1 AND account_id = $2
`

type GetCampaignByIDParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) GetCampaignByID(ctx context.Context, arg GetCampaignByIDParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaignByID, arg.ID, arg.AccountID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Text,
		&i.TotalRecipients,
		&i.CostPerMessage,
		&i.TotalCost,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaignsByAccount = `-- name: ListCampaignsByAccount :many
SELECT id, account_id, text, total_recipients, cost_per_message, total_cost, status, created_at, updated_at
FROM campaigns
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListCampaignsByAccountParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListCampaignsByAccount(ctx context.Context, arg ListCampaignsByAccountParams) ([]Campaign, error) {
	rows, err := q.db.Query(ctx, listCampaignsByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Campaign
	for rows.Next() {
		var i Campaign
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Text,
			&i.TotalRecipients,
			&i.CostPerMessage,
			&i.TotalCost,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaignStatus = `-- name: UpdateCampaignStatus :exec
UPDATE campaigns
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateCampaignStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateCampaignStatus(ctx context.Context, arg UpdateCampaignStatusParams) error {
	_, err := q.db.Exec(ctx, updateCampaignStatus, arg.ID, arg.Status)
	return err
}
