// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: ledger_entries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const insertLedgerEntry = `-- name: InsertLedgerEntry :one
INSERT INTO ledger_entries (account_id, type, amount, message_id)
VALUES ($1, $2, $3, $4)
RETURNING id, account_id, type, amount, message_id, created_at, updated_at
`

type InsertLedgerEntryParams struct {
	AccountID uuid.UUID  `json:"account_id"`
	Type      string     `json:"type"`
	Amount    int64      `json:"amount"`
	MessageID *uuid.UUID `json:"message_id"`
}

func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.AccountID,
		arg.Type,
		arg.Amount,
		arg.MessageID,
	)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Type,
		&i.Amount,
		&i.MessageID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, account_id, type, amount, message_id, created_at, updated_at
FROM ledger_entries
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerEntriesByAccountParams struct {
	AccountID uuid.UUID `json:"account_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, arg ListLedgerEntriesByAccountParams) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount, arg.AccountID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LedgerEntry
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Type,
			&i.Amount,
			&i.MessageID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumLedgerEntriesByAccount = `-- name: SumLedgerEntriesByAccount :one
SELECT COALESCE(SUM(amount), 0)::bigint AS balance
FROM ledger_entries
WHERE account_id = $1
`

// The ground truth for an account's balance - used by the reconciler
// and by cold-start Redis bootstrap (ARCHITECTURE.md section 5.3).
func (q *Queries) SumLedgerEntriesByAccount(ctx context.Context, accountID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, sumLedgerEntriesByAccount, accountID)
	var balance int64
	err := row.Scan(&balance)
	return balance, err
}
