// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: messages.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (id, account_id, campaign_id, recipient, priority, cost, status, deadline_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id, created_at) DO NOTHING
RETURNING id, account_id, campaign_id, recipient, priority, cost, status, operator, deadline_at, dispatched_at, created_at, updated_at
`

type CreateMessageParams struct {
	ID         uuid.UUID          `json:"id"`
	AccountID  uuid.UUID          `json:"account_id"`
	CampaignID *uuid.UUID         `json:"campaign_id"`
	Recipient  string             `json:"recipient"`
	Priority   string             `json:"priority"`
	Cost       int64              `json:"cost"`
	Status     string             `json:"status"`
	DeadlineAt pgtype.Timestamptz `json:"deadline_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// `created_at` is passed explicitly (not defaulted) so that retried Campaign
// Expander runs are idempotent: the composite primary key is (id, created_at),
// and every retry must reuse the same accepted_at timestamp for the same
// deterministic message id, or ON CONFLICT would never match. See
// ARCHITECTURE.md section 9.2 and .cursor/rules/kafka-consumer-conventions.mdc.
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ID,
		arg.AccountID,
		arg.CampaignID,
		arg.Recipient,
		arg.Priority,
		arg.Cost,
		arg.Status,
		arg.DeadlineAt,
		arg.CreatedAt,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CampaignID,
		&i.Recipient,
		&i.Priority,
		&i.Cost,
		&i.Status,
		&i.Operator,
		&i.DeadlineAt,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageByIDForAccount = `-- name: GetMessageByIDForAccount :one
SELECT id, account_id, campaign_id, recipient, priority, cost, status, operator, deadline_at, dispatched_at, created_at, updated_at
FROM messages
WHERE id = $1 AND account_id = $2
`

type GetMessageByIDForAccountParams struct {
	ID        uuid.UUID `json:"id"`
	AccountID uuid.UUID `json:"account_id"`
}

func (q *Queries) GetMessageByIDForAccount(ctx context.Context, arg GetMessageByIDForAccountParams) (Message, error) {
	row := q.db.QueryRow(ctx, getMessageByIDForAccount, arg.ID, arg.AccountID)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CampaignID,
		&i.Recipient,
		&i.Priority,
		&i.Cost,
		&i.Status,
		&i.Operator,
		&i.DeadlineAt,
		&i.DispatchedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertMessageStatusEvent = `-- name: InsertMessageStatusEvent :exec
INSERT INTO message_status_events (message_id, status, occurred_at)
VALUES ($1, $2, $3)
`

type InsertMessageStatusEventParams struct {
	MessageID  uuid.UUID          `json:"message_id"`
	Status     string             `json:"status"`
	OccurredAt pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertMessageStatusEvent(ctx context.Context, arg InsertMessageStatusEventParams) error {
	_, err := q.db.Exec(ctx, insertMessageStatusEvent, arg.MessageID, arg.Status, arg.OccurredAt)
	return err
}

const listMessagesByCampaign = `-- name: ListMessagesByCampaign :many
SELECT id, account_id, campaign_id, recipient, priority, cost, status, operator, deadline_at, dispatched_at, created_at, updated_at
FROM messages
WHERE campaign_id = $1 AND account_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListMessagesByCampaignParams struct {
	CampaignID *uuid.UUID `json:"campaign_id"`
	AccountID  uuid.UUID  `json:"account_id"`
	Limit      int32      `json:"limit"`
	Offset     int32      `json:"offset"`
}

func (q *Queries) ListMessagesByCampaign(ctx context.Context, arg ListMessagesByCampaignParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByCampaign,
		arg.CampaignID,
		arg.AccountID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CampaignID,
			&i.Recipient,
			&i.Priority,
			&i.Cost,
			&i.Status,
			&i.Operator,
			&i.DeadlineAt,
			&i.DispatchedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMessageStatus = `-- name: UpdateMessageStatus :exec
UPDATE messages
SET status = $3, operator = $4, dispatched_at = $5, updated_at = now()
WHERE id = $1 AND created_at = $2
`

type UpdateMessageStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	Status       string             `json:"status"`
	Operator     pgtype.Text        `json:"operator"`
	DispatchedAt pgtype.Timestamptz `json:"dispatched_at"`
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error {
	_, err := q.db.Exec(ctx, updateMessageStatus,
		arg.ID,
		arg.CreatedAt,
		arg.Status,
		arg.Operator,
		arg.DispatchedAt,
	)
	return err
}
