// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: processed_events.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const markEventProcessed = `-- name: MarkEventProcessed :one
INSERT INTO processed_events (consumer_name, event_id)
VALUES ($1, $2)
ON CONFLICT (consumer_name, event_id) DO NOTHING
RETURNING consumer_name, event_id, processed_at
`

type MarkEventProcessedParams struct {
	ConsumerName string `json:"consumer_name"`
	EventID      string `json:"event_id"`
}

type MarkEventProcessedRow struct {
	ConsumerName string             `json:"consumer_name"`
	EventID      string             `json:"event_id"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
}

// Returns false (no row) if the event was already processed - caller should
// skip the side effect but still commit the Kafka offset. Must run in the same
// transaction as the business write it guards. See ARCHITECTURE.md section 5.2.
func (q *Queries) MarkEventProcessed(ctx context.Context, arg MarkEventProcessedParams) (MarkEventProcessedRow, error) {
	row := q.db.QueryRow(ctx, markEventProcessed, arg.ConsumerName, arg.EventID)
	var i MarkEventProcessedRow
	err := row.Scan(&i.ConsumerName, &i.EventID, &i.ProcessedAt)
	return i, err
}
