// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: topup_idempotency.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const getTopupIdempotency = `-- name: GetTopupIdempotency :one
SELECT account_id, idempotency_key, amount, durable_balance, created_at, updated_at
FROM topup_idempotency
WHERE account_id = $1 AND idempotency_key = $2
`

type GetTopupIdempotencyParams struct {
	AccountID      uuid.UUID `json:"account_id"`
	IdempotencyKey string    `json:"idempotency_key"`
}

func (q *Queries) GetTopupIdempotency(ctx context.Context, arg GetTopupIdempotencyParams) (TopupIdempotency, error) {
	row := q.db.QueryRow(ctx, getTopupIdempotency, arg.AccountID, arg.IdempotencyKey)
	var i TopupIdempotency
	err := row.Scan(
		&i.AccountID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.DurableBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTopupIdempotencyBalance = `-- name: SetTopupIdempotencyBalance :exec
UPDATE topup_idempotency
SET durable_balance = $3, updated_at = now()
WHERE account_id = $1 AND idempotency_key = $2
`

type SetTopupIdempotencyBalanceParams struct {
	AccountID      uuid.UUID `json:"account_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	DurableBalance int64     `json:"durable_balance"`
}

func (q *Queries) SetTopupIdempotencyBalance(ctx context.Context, arg SetTopupIdempotencyBalanceParams) error {
	_, err := q.db.Exec(ctx, setTopupIdempotencyBalance, arg.AccountID, arg.IdempotencyKey, arg.DurableBalance)
	return err
}

const tryInsertTopupIdempotency = `-- name: TryInsertTopupIdempotency :one
INSERT INTO topup_idempotency (account_id, idempotency_key, amount, durable_balance)
VALUES ($1, $2, $3, 0)
ON CONFLICT (account_id, idempotency_key) DO NOTHING
RETURNING account_id, idempotency_key, amount, durable_balance, created_at, updated_at
`

type TryInsertTopupIdempotencyParams struct {
	AccountID      uuid.UUID `json:"account_id"`
	IdempotencyKey string    `json:"idempotency_key"`
	Amount         int64     `json:"amount"`
}

func (q *Queries) TryInsertTopupIdempotency(ctx context.Context, arg TryInsertTopupIdempotencyParams) (TopupIdempotency, error) {
	row := q.db.QueryRow(ctx, tryInsertTopupIdempotency, arg.AccountID, arg.IdempotencyKey, arg.Amount)
	var i TopupIdempotency
	err := row.Scan(
		&i.AccountID,
		&i.IdempotencyKey,
		&i.Amount,
		&i.DurableBalance,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
